# -*- coding: utf-8 -*-
"""Mock2_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AcPMOaYkBo7uIrPJwVU_sq6aszgzowu7

Sure, here is the function called `calculate_mean` that takes a list of numbers as input and returns the mean(average) of the numbers using the sum of the numbers divided by the total count:
"""

def calculate_mean(numbers):
  """
  Calculates the mean of a list of numbers.

  Args:
    numbers: A list of numbers.

  Returns:
    The mean of the numbers.
  """

  sum_of_numbers = 0
  count = len(numbers)
  for number in numbers:
    sum_of_numbers += number
  mean = sum_of_numbers / count
  return mean


def main():
  numbers = [1, 2, 3, 4, 5]
  mean = calculate_mean(numbers)
  print(mean)


if __name__ == "__main__":
  main()

"""This function first gets the sum of the numbers in the list. Then, it divides the sum by the total count of numbers in the list. The result is then returned.

To run the function, you can save it as a Python file and then run it from the command line. For example, if you save the function as `calculate_mean.py`, you can run it by typing the following command into the command line:

```
python calculate_mean.py
```

This will print the mean of the numbers in the list.
"""